package com.program.file_conversion_service.api.dto;

import io.swagger.v3.oas.annotations.media.Schema;

public record UploadConversionRequest(
        @Schema(description = "Optional task identifier. If omitted, a new UUID is generated by the service.", example = "c24b3947-b35f-46a4-8e5d-becfae94ea77")
        String taskId,
        @Schema(description = "Optional destination bucket for the uploaded source file. If omitted, the default source bucket is used.", example = "files")
        String bucket,
        @Schema(description = "Optional source file type. If omitted, the service tries to resolve it from the uploaded file name.", example = "PNG")
        String fileType
) { }
